---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность полноценно оформить заказ, заполнив важную для оформления заказа информацию (например ФИО, контактные данные, способ доставки и оплаты).
  - Пользователь должен иметь возможность удалить товар из корзины.
  - Пользователь должен иметь возможность из корзины вернуться в каталог товаров и продолжить выбирать товары.
  - При повторном заходе или обновлении страницы товары, добавленные в корзину, должны сохраниться.
  - После добавления товара в корзину пользователь должен иметь возможность вернуться к списку товаров и продолжить покупки.
  - Пользователь должен иметь возможность пользоваться постраничным выводом товаров.
